baseURL = "http://sistem.org/"
languageCode = "en-us"
title = "SISTEM"
sectionPagesMenu = "main"

[Params]
  description = "a event ran by students, for students."
  favicon = "favicon.ico"
  repo = "redbrick/sistem"
  location = "Bank Of Ireland, Grand Canal Dock"
  date = "2018-03-24T09:00:00"
  video = ""
