baseURL = "http://sistem.org/"
languageCode = "en-us"
title = "SISTEM"
sectionPagesMenu = "main"

[Params]
  description = "An event ran by students, for students."
  favicon = "favicon.ico"
  repo = "redbrick/sistem"
  location = "Trinity Innovation Academy"
  map = "https://goo.gl/maps/HMQ8QufzZ7S2"
  date = "2018-03-24T09:00:00"
  twitter = "redbrickdcu"
