baseURL = "http://sistem.org/"
languageCode = "en-us"
title = "SISTEM"
sectionPagesMenu = "main"

[Params]
  description = "An event ran by students, for students."
  favicon = "favicon.ico"
  repo = "redbrick/sistem"
  location = "Bank Of Ireland, Grand Canal Dock"
  map = "https://goo.gl/maps/Wyyf4N2KH452"
  date = "2018-03-24T09:00:00"
  twitter = "redbrickdcu"
  organisers = [
    "DUCSS",
    "Redbrick",
    "DIT Compsoc",
    "DU Netsoc"
  ]
