---
version: 2
jobs:
  build:
    working_directory: ~/sistem
    docker:
      - image: circleci/node:8-browsers
        environment:
          LANG: en_US.utf8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: "Setup Git"
          command: |
            set -e
            mkdir public
            cd public
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1
            git init
            git remote add --fetch origin "$remote"
            git checkout gh-pages
      - run:
          name: "Build Site"
          command: yarn build
